/**
 * Exchange Auto-Sync — ccxt lazy-loading root.
 *
 * This is the ONLY module that does `await import('ccxt')` (memoized), which
 * keeps the ~MB vendor-ccxt chunk out of the app's entry graph — every other
 * module uses `import type` from here only.
 */
import type { ExchangeConnectionRow } from '@/lib/storage/db';
import { isSaasMode } from '@/lib/saas/config';
import { installTunnelFetch, TunnelError } from './tunnel';
import type { ExchangeId, SyncErrorKind } from './types';

// ---- ccxt module handle (structural — avoids pulling ccxt types in eagerly) ----

interface CcxtExchangeCtor {
  new (config: Record<string, unknown>): unknown;
}

interface CcxtModule {
  [exchangeId: string]: CcxtExchangeCtor | unknown;
}

let ccxtPromise: Promise<CcxtModule> | null = null;
/** Resolved ccxt module, kept for synchronous instanceof checks (BUG-1). */
let ccxtModule: CcxtModule | null = null;

/** Lazily load (and memoize) the ccxt ESM bundle. */
export function loadCcxt(): Promise<CcxtModule> {
  if (!ccxtPromise) {
    ccxtPromise = (import('ccxt') as unknown as Promise<CcxtModule>).then((m) => {
      ccxtModule = m;
      return m;
    });
  }
  return ccxtPromise;
}

// ---- Structural shapes (subset of ccxt's unified structures we consume) ----

export interface UnifiedMarket {
  symbol: string;
  /** Exchange-native market id (e.g. 'BTCUSDT', 'BTC-USDT', 'XXBTZUSD'). */
  id?: string;
  base: string;
  quote: string;
  spot?: boolean;
  active?: boolean;
}

export interface UnifiedTrade {
  id?: string;
  order?: string;
  timestamp?: number;
  symbol?: string;
  side?: string;
  price?: number;
  amount?: number;
  cost?: number;
  fee?: { cost?: number; currency?: string };
  info?: Record<string, unknown>;
}

export interface UnifiedTransfer {
  id?: string;
  txid?: string;
  timestamp?: number;
  currency?: string;
  amount?: number;
  status?: string;
  type?: string;
  address?: string;
  addressTo?: string;
  addressFrom?: string;
  network?: string;
  fee?: { cost?: number; currency?: string };
  info?: Record<string, unknown>;
}

/** ccxt Balances structure (subset): per-asset {free, used, total} + 'total' dict. */
export interface UnifiedBalance {
  free?: Record<string, number | undefined>;
  used?: Record<string, number | undefined>;
  total?: Record<string, number | undefined>;
  info?: unknown;
  [asset: string]: unknown;
}

/** The subset of a ccxt exchange instance the engine drives. */
export interface ExchangeClient {
  id: string;
  markets?: Record<string, UnifiedMarket>;
  /** Enabled for HTX so pagination can use the raw response's final item before CCXT sorts parsed rows. */
  last_json_response?: unknown;
  /** BTC Markets exposes its native pagination cursors only in response headers. */
  last_response_headers?: Record<string, string>;
  /** Pinned MEXC public offline-symbol endpoint generated by CCXT. */
  spotPublicGetSymbolOffline?(params?: Record<string, unknown>): Promise<unknown>;
  loadMarkets(reload?: boolean): Promise<Record<string, UnifiedMarket>>;
  fetchBalance(params?: Record<string, unknown>): Promise<UnifiedBalance>;
  fetchMyTrades(
    symbol?: string,
    since?: number,
    limit?: number,
    params?: Record<string, unknown>
  ): Promise<UnifiedTrade[]>;
  fetchDeposits(
    code?: string,
    since?: number,
    limit?: number,
    params?: Record<string, unknown>
  ): Promise<UnifiedTransfer[]>;
  fetchWithdrawals(
    code?: string,
    since?: number,
    limit?: number,
    params?: Record<string, unknown>
  ): Promise<UnifiedTransfer[]>;
  /** Bitfinex exposes deposits and withdrawals through one Movements endpoint. */
  fetchDepositsWithdrawals?(
    code?: string,
    since?: number,
    limit?: number,
    params?: Record<string, unknown>
  ): Promise<UnifiedTransfer[]>;
  handleRestResponse(...args: unknown[]): unknown;
  fetch(url: string, method?: string, headers?: Record<string, string>, body?: string): Promise<unknown>;
}

/** Display labels for plain-language error copy. */
const EXCHANGE_LABELS: Record<ExchangeId, string> = {
  binance: 'Binance',
  coinbase: 'Coinbase',
  kraken: 'Kraken',
  okx: 'OKX',
  kucoin: 'KuCoin',
  bybit: 'Bybit',
  gateio: 'Gate.io',
  htx: 'HTX',
  cryptocom: 'Crypto.com Exchange',
  bitfinex: 'Bitfinex',
  gemini: 'Gemini',
  btcmarkets: 'BTC Markets',
  mexc: 'MEXC'
};

export function exchangeLabel(exchange: ExchangeId): string {
  return EXCHANGE_LABELS[exchange];
}

/**
 * Create a ccxt client for a saved connection row, with the tunnel transport
 * installed. Constructor config per contract C5:
 * `enableRateLimit: true, timeout: 30000`; binance/okx also
 * `options: { defaultType: 'spot' }`; passphrase maps to ccxt `password`.
 * Throws TunnelError('not_hosted') outside hosted mode.
 */
export async function createExchangeClient(row: ExchangeConnectionRow): Promise<ExchangeClient> {
  if (!isSaasMode()) {
    throw new TunnelError('not_hosted');
  }
  const exchangeId = row.exchange as ExchangeId;
  const ccxt = await loadCcxt();
  // SoloLedger's stable id follows the existing CSV parser (`gateio`), while
  // CCXT 4.5.68 exports Gate.io as the `gate` class.
  const ccxtClassId = exchangeId === 'gateio' ? 'gate' : exchangeId;
  const Ctor = ccxt[ccxtClassId] as CcxtExchangeCtor | undefined;
  if (!Ctor) {
    throw new TunnelError('relay_unavailable', `ccxt has no exchange implementation for '${exchangeId}'.`);
  }
  const config: Record<string, unknown> = {
    apiKey: row.apiKey,
    secret: row.secret,
    enableRateLimit: true,
    timeout: 30_000
  };
  if (row.passphrase) config.password = row.passphrase;
  if (exchangeId === 'binance' || exchangeId === 'okx' || exchangeId === 'bybit' || exchangeId === 'gateio' || exchangeId === 'htx' || exchangeId === 'cryptocom' || exchangeId === 'bitfinex' || exchangeId === 'gemini' || exchangeId === 'btcmarkets' || exchangeId === 'mexc') {
    // Spot-only scope: defaultType alone is NOT enough — ccxt's loadMarkets
    // otherwise also fetches linear/inverse (binance: fapi/dapi hosts, which
    // the relay's spot-only host map would reject; okx: 4x the instrument
    // calls). Restrict the markets fetch to spot explicitly.
    config.options = exchangeId === 'bybit'
      ? {
          defaultType: 'spot',
          fetchMarkets: { types: ['spot'] },
          // Current Bybit accounts use UTA. Pinning this prevents ccxt's
          // isUnifiedEnabled() probe from making two extra signed account/API
          // metadata requests before the one balance call we actually need.
          enableUnifiedMargin: false,
          enableUnifiedAccount: true,
          unifiedMarginStatus: 6
        }
      : exchangeId === 'gateio'
        ? {
            defaultType: 'spot',
            fetchMarkets: { types: ['spot'] },
            // Avoid Gate's signed /unified/unified_mode account probe. The
            // connector is intentionally classic spot-only.
            unifiedAccount: false,
            fetchCurrencies: false
          }
        : exchangeId === 'htx'
          ? {
              defaultType: 'spot',
              fetchMarkets: { types: { spot: true, linear: false, inverse: false } },
              // Market symbols are sufficient for sync. Avoid the unrelated
              // currency/reference probe and pin every account call to spot.
              fetchCurrencies: false,
              // HTX's transaction parser expects these maps to have been
              // initialized by fetchCurrencies. A sentinel keeps its normal
              // raw-chain fallback working without that unnecessary probe.
              networkNamesByChainIds: { __sololedger__: '__sololedger__' },
              networkChainIdsByNames: { __sololedger__: {} }
            }
          : exchangeId === 'cryptocom'
            ? {
                defaultType: 'spot',
                // Crypto.com returns spot and derivatives from one public
                // instruments endpoint. The engine retains only active spot
                // markets and independently filters every private trade row.
                skipFetchCurrencies: true,
                fetchCurrencies: false
              }
          : exchangeId === 'bitfinex'
            ? {
                defaultType: 'spot',
                fetchCurrencies: false
              }
          : exchangeId === 'gemini'
            ? {
                defaultType: 'spot',
                fetchCurrencies: false,
                // Gemini's API symbols catalog is the complete spot market
                // universe needed by the symbol-required mytrades endpoint.
                fetchMarketsMethod: 'fetch_markets_from_api'
              }
          : exchangeId === 'btcmarkets'
            ? {
                defaultType: 'spot',
                // The pinned class has no currency endpoint. Keep market
                // discovery to the one public /v3/markets call.
                fetchCurrencies: false
              }
          : exchangeId === 'mexc'
            ? {
                defaultType: 'spot',
                fetchCurrencies: false
              }
        : { defaultType: 'spot', fetchMarkets: ['spot'] };
  }
  if (exchangeId === 'binance') {
    // ccxt's binance fetchCurrencies (default on when credentials exist)
    // hits signed SAPI endpoints incl. /sapi/v1/margin/allPairs — extra
    // relay traffic we never use (the engine discovers assets from the
    // balance + transfers, not currencies). Disable it. Likewise binance
    // defaults options.fetchMargins = true, which makes fetchMarkets pull
    // cross/isolated margin pair lists from SAPI when credentials exist.
    (config.options as Record<string, unknown>).fetchCurrencies = false;
    (config.options as Record<string, unknown>).fetchMargins = false;
  }
  if (exchangeId === 'bybit') {
    // Bybit's fetchCurrencies is a signed asset endpoint unrelated to the
    // spot history engine and broadens the relay surface unnecessarily.
    (config.options as Record<string, unknown>).fetchCurrencies = false;
    // ccxt base loadMarkets checks `has.fetchCurrencies`, not the option, for
    // Bybit. Override the capability as well so the signed coin-info endpoint
    // is never called.
    config.has = { fetchCurrencies: false };
  }
  if (exchangeId === 'gateio') {
    // Gate's public currencies response is not needed for our market/trade
    // normalization. Pin the capability off as well as the option so
    // loadMarkets performs only the spot currency-pairs request.
    config.has = { fetchCurrencies: false };
  }
  if (exchangeId === 'htx' || exchangeId === 'gemini') {
    config.has = { fetchCurrencies: false };
    config.enableLastJsonResponse = true;
  }
  if (exchangeId === 'cryptocom') {
    config.has = { fetchCurrencies: false };
  }
  if (exchangeId === 'bitfinex') {
    config.has = { fetchCurrencies: false };
  }
  if (exchangeId === 'btcmarkets') {
    config.has = { fetchCurrencies: false };
    config.enableLastJsonResponse = true;
    config.enableLastResponseHeaders = true;
  }
  if (exchangeId === 'mexc') {
    config.has = { fetchCurrencies: false };
    config.enableLastJsonResponse = true;
  }
  const exchange = new Ctor(config) as ExchangeClient;
  if (exchangeId === 'mexc') {
    // CCXT 4.5.68's generic fetchMarkets always runs spot and swap in
    // parallel. Pin loadMarkets to this exact class revision's spot parser so
    // /api/v1/contract/detail can never be emitted by the connector.
    const raw = exchange as unknown as {
      fetchMarkets: (params?: Record<string, unknown>) => Promise<UnifiedMarket[]>;
      fetchSpotMarkets: (params?: Record<string, unknown>) => Promise<UnifiedMarket[]>;
    };
    raw.fetchMarkets = (params = {}) => raw.fetchSpotMarkets(params);
  }
  if (exchangeId === 'bitfinex') {
    // Bitfinex defaults its public v2 URL to api-pub.bitfinex.com. Keep both
    // public and private calls on the relay's one exact spot host.
    const raw = exchange as unknown as { urls: { api: Record<string, string> } };
    raw.urls.api.v1 = 'https://api.bitfinex.com';
    raw.urls.api.public = 'https://api.bitfinex.com';
    raw.urls.api.private = 'https://api.bitfinex.com';
  }
  if (exchangeId === 'gateio') {
    // CCXT's Gate fetchSpotMarkets always joins public margin/currency_pairs
    // into the spot response. Margin metadata is irrelevant here and the
    // relay deliberately blocks that path, so satisfy the join locally.
    (exchange as unknown as { publicMarginGetCurrencyPairs: () => Promise<unknown[]> })
      .publicMarginGetCurrencyPairs = async () => [];
  }
  installTunnelFetch(exchange, exchangeId);
  return exchange;
}

// ---- Error classification ----

/** All ccxt error-class names up an error's prototype chain. */
function errorClassNames(err: unknown): Set<string> {
  const names = new Set<string>();
  // ccxt error classes assign their semantic name to the INSTANCE
  // (`this.name = 'AuthenticationError'`), which survives minification —
  // unlike the class binding name. Collect it at the leaf.
  const own = (err as { name?: unknown } | null)?.name;
  if (typeof own === 'string') names.add(own);
  let proto: object | null = err as object;
  while (proto && proto !== Object.prototype) {
    const ctor = (proto as { constructor?: { name?: string } }).constructor;
    if (ctor?.name) names.add(ctor.name);
    proto = Object.getPrototypeOf(proto) as object | null;
  }
  return names;
}

/**
 * True when the error is (a subclass of) one of the named ccxt error classes.
 *
 * Minification-proof (BUG-1): production builds rename class bindings
 * (`class D extends O`), so `constructor.name` matching silently fails and
 * every ccxt error classified as 'unknown' on the live site. When the ccxt
 * module is loaded (always true once a client exists — clients are created
 * before any error can be classified), match by `instanceof` against the real
 * error classes, which is name-independent and subclass-aware. The name-based
 * walk remains as a fallback for errors raised before the module resolves
 * (e.g. a chunk-load failure).
 */
export function hasErrorName(err: unknown, ...names: string[]): boolean {
  if (ccxtModule && (err as object | null) instanceof Error) {
    const matched = names.some((n) => {
      const ctor = (ccxtModule as Record<string, unknown>)[n];
      return typeof ctor === 'function' && err instanceof (ctor as new () => Error);
    });
    if (matched) return true;
  }
  const all = errorClassNames(err);
  return names.some((n) => all.has(n));
}

/**
 * Map any sync failure to a SyncErrorKind. TunnelError kinds pass through;
 * ccxt error classes map to their bucket (subclass-aware, so e.g.
 * AccountSuspended → invalid_key via its AuthenticationError parent).
 */
export function classifySyncError(err: unknown): SyncErrorKind {
  if (err instanceof TunnelError) return err.kind;
  if (hasErrorName(err, 'AccountNotEnabled', 'PermissionDenied')) return 'permission';
  if (hasErrorName(err, 'AuthenticationError')) return 'invalid_key';
  if (hasErrorName(err, 'RateLimitExceeded', 'DDoSProtection')) return 'rate_limit';
  // Geo-block (Binance HTTP 451 'Service unavailable from a restricted
  // location') surfaces as ExchangeNotAvailable — a NetworkError — but it is
  // NOT a transient network issue: it is non-retryable and needs its own
  // copy, so check for it before the generic network mapping.
  const message = err instanceof Error ? err.message : String(err ?? '');
  if (/\b10072\b|api key info invalid/i.test(message)) return 'invalid_key';
  if (/restricted location/i.test(message)) return 'region_blocked';
  // A malformed secret can crash signing LOCALLY before any request is sent
  // (e.g. Kraken's base64 HMAC secret decode: "padding: invalid…", or the
  // browser atob variant "not correctly encoded"). That IS a key problem —
  // point the user at the key instead of the generic fallback.
  if (/padding: invalid|not correctly encoded|invalid base64/i.test(message)) return 'invalid_key';
  if (hasErrorName(err, 'NetworkError', 'ExchangeNotAvailable', 'RequestTimeout')) return 'network';
  return 'unknown';
}

/** Plain-language message for a classified sync error. */
export function syncErrorMessage(kind: SyncErrorKind, exchange: ExchangeId): string {
  const label = exchangeLabel(exchange);
  switch (kind) {
    case 'not_hosted':
      return 'Auto-sync needs Hosted mode — switch modes or use CSV import.';
    case 'relay_auth':
      return 'Your session has expired — please sign in again.';
    case 'relay_subscription':
      return 'Auto-sync needs an active SoloLedger subscription.';
    case 'relay_disabled':
      return 'Auto-sync is temporarily unavailable — please use CSV import.';
    case 'relay_payload':
      return 'The request was too large for the relay — please try again.';
    case 'relay_unavailable':
      return 'The SoloLedger relay could not reach the exchange — please try again in a moment.';
    case 'invalid_key':
      return `API key or secret rejected by ${label} — check the key and try again.`;
    case 'permission':
      return `${label} says this key lacks read permission — create a read-only key (disable trading and withdrawals).`;
    case 'rate_limit':
      return `${label} rate-limited the sync — it will pick up where it left off on the next try.`;
    case 'network':
      return `Network error talking to ${label} — check your connection and try again.`;
    case 'region_blocked':
      return `${label} currently can't be reached from SoloLedger's servers — ${label} blocks our hosting region. We're fixing this. Please use CSV import for ${label} for now.`;
    case 'unknown':
      return `Something went wrong while syncing ${label} — please try again.`;
  }
}
