import { AlertTriangle } from 'lucide-react';
import { formatCompactAmount, formatCurrency } from '@/lib/utils';
import type { TransactionCostAnalysisModel } from './transactionCostAnalysisModel';
const money = (value: number | undefined, currency: string) => value == null ? 'N/A — unpriced' : formatCurrency(value, currency);

export function TransactionCostAnalysisTab({ model }: { model: TransactionCostAnalysisModel }) {
  return <div role="tabpanel" id="transaction-panel-cost" aria-labelledby="transaction-tab-cost" className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_310px]">
    <section className="overflow-hidden rounded-2xl border border-hi/10 bg-elev-1">
      <header className="flex flex-wrap items-start justify-between gap-3 border-b border-hi/10 px-4 py-4 sm:px-5"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.08em] text-low">{model.method} match</p><h3 className="mt-1 text-base font-extrabold text-hi">Cost analysis</h3><p className="mt-1 text-xs text-low">How the configured report models present this transaction in {model.currency}.</p></div><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">{model.jurisdictionLabel} · {model.currency}</span></header>
      <div className="grid sm:grid-cols-3"><Metric label={model.businessIncome != null ? 'Business income' : 'Proceeds'} value={money(model.businessIncome ?? model.proceeds, model.currency)} /><Metric label={model.businessExpense != null ? 'Business expense' : model.costBasisCompleteness === 'partial' ? 'Allowable cost (partial)' : 'Allowable cost'} value={money(model.businessExpense ?? model.costBasis, model.currency)} border /><Metric label="Raw gain / loss" value={money(model.eventTreatment?.rawGain ?? model.gain, model.currency)} /></div>
      {model.eventTreatment && <div className="grid border-t border-hi/10 sm:grid-cols-3" data-testid="event-tax-treatment"><Metric label={model.eventTreatment.inclusionRate != null ? 'Included taxable gain' : 'Taxable result'} value={formatCurrency(model.eventTreatment.taxableGain, model.currency)} /><Metric label="Disallowed loss" value={formatCurrency(model.eventTreatment.disallowedLoss, model.currency)} border /><Metric label="Holding-period treatment" value={model.eventTreatment.shortTermGain != null ? `${formatCurrency(model.eventTreatment.shortTermGain, model.currency)} short · ${formatCurrency(model.eventTreatment.longTermGain ?? 0, model.currency)} long` : model.eventTreatment.inclusionRate != null ? `${model.eventTreatment.inclusionRate * 100}% inclusion` : 'No holding-period split'} /></div>}
      <div className="border-t border-hi/10 px-4 py-4 sm:px-5"><p className="text-[10px] font-extrabold uppercase tracking-[0.08em] text-low">Matched acquisition lots</p><h4 className="mt-1 text-sm font-extrabold text-hi">{model.disposedQuantity != null ? `${formatCompactAmount(model.disposedQuantity)} ${model.disposedAsset} disposed` : 'No disposal lot match'}</h4></div>
      {model.matchedRows.length > 0 ? <div className="overflow-x-auto border-t border-hi/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50" role="region" aria-label="Matched acquisition lots table" tabIndex={0}><table className="w-full min-w-[700px] text-xs"><thead className="bg-elev-3/60 text-left text-[10px] uppercase tracking-wide text-low"><tr><th className="px-3 py-2">Acquired</th><th className="px-3 py-2">Source</th><th className="px-3 py-2 text-right">Quantity used</th><th className="px-3 py-2 text-right">Unit cost</th><th className="px-3 py-2 text-right">Cost basis</th></tr></thead><tbody>{model.matchedRows.map((row) => <tr key={row.id} className="border-t border-hi/10"><td className="px-3 py-3">{row.buyTxId ? new Date(row.buyDate).toLocaleDateString() : 'N/A'}</td><td className="px-3 py-3 font-semibold text-hi">{row.sourceLabel}<span className="block font-normal capitalize text-low">{row.acquisitionType}</span></td><td className="px-3 py-3 text-right">{formatCompactAmount(row.sellAmount)} {row.asset}</td><td className="px-3 py-3 text-right">{row.status === 'missing_cost_basis' ? 'N/A — missing acquisition' : row.unitCost == null ? 'N/A — unpriced' : formatCurrency(row.unitCost, model.currency)}</td><td className="px-3 py-3 text-right">{row.status === 'missing_cost_basis' ? 'N/A — missing acquisition' : row.costBasis == null ? 'N/A — unpriced' : formatCurrency(row.costBasis, model.currency)}</td></tr>)}</tbody></table></div> : <p className="border-t border-hi/10 px-5 py-6 text-xs text-low">No matched acquisition rows apply to this transaction.</p>}
    </section>
    <aside className="space-y-3"><section className="rounded-2xl border border-hi/10 bg-elev-1 p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.08em] text-low">Calculation</p><h3 className="mt-2 text-sm font-extrabold text-hi">{model.proceeds != null && model.costBasis != null ? `${formatCurrency(model.proceeds, model.currency)} − ${formatCurrency(model.costBasis, model.currency)}` : model.derivativeTreatment ?? model.classification}</h3><p className="mt-2 text-xs leading-relaxed text-low">{model.classification} · {model.yearConvention} · {model.method}.</p></section>
      <section className="rounded-2xl border border-hi/10 bg-elev-1 p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.08em] text-low">Valuation illustrations</p><ul className="mt-2 space-y-2">{model.valuations.map((row) => <li key={row.kind} className="flex justify-between gap-3 text-xs"><span className="capitalize text-low">{row.kind.replace(/_/g, ' ')}</span><strong className="text-right text-hi">{row.amount == null ? row.completeness === 'partial' ? 'N/A — non-fiat fee' : 'N/A — unpriced' : formatCurrency(row.amount, row.currency)}</strong></li>)}</ul></section>
      {model.warnings.map((warning) => <div key={warning} role="status" className="flex gap-2 rounded-xl border border-warn/25 bg-warn/10 px-3 py-3 text-xs text-mid"><AlertTriangle className="h-4 w-4 shrink-0 text-warn" aria-hidden="true" />{warning}</div>)}
      <p className="rounded-xl border border-primary/20 bg-primary/[0.05] px-3 py-3 text-xs leading-relaxed text-low"><strong className="text-mid">Tax-safe boundary:</strong> reconciliation postings, opening balances, and authority quantities never create lots, proceeds, basis, or gains.</p>
    </aside>
  </div>;
}
function Metric({ label, value, border }: { label: string; value: string; border?: boolean }) { return <div className={`p-4 ${border ? 'sm:border-x sm:border-hi/10' : ''}`}><p className="text-[10px] font-bold uppercase tracking-wide text-low">{label}</p><p className="mt-1 text-base font-extrabold tabular-figures text-hi">{value}</p></div>; }
